
sass:
  dir: _sass
  style: compressed  

css_dir: "/style"

plugins:
  - jekyll-postcss

postcss:
  cache: false

collections:
  posts: 
    output: true
    permalink: /posts/:slug
  cats: 
    output: true

_select_data:
  video-types:
    - vimeo
    - youtube
    - self-hosted
  section-styles:
    p-4: Padded Sm
    p-6: Padded Md
    p-8: Padded Lg
  positions:
    - left
    - right
  backgrounds:
    bg-zinc-800: Dark Background
    bg-gray-300: Gray Background
    bg-gray-50: Light Background 
  
 
# Hides frontmatter from clients 
# Single select
_inputs:
  layout:
    hidden: true
  # cats:
  #   type: multi-select
  #   options:
  #     values: collections.cats
  # grid-width: 
  # column-width:

page_blocks: []

_array_structures:
 page_blocks:
  - label: Banner Block
    icon: article
    value: 
      _id: banner
      title: Image Banner
      banner_image: https://images.unsplash.com/photo-1557093793-e196ae071479?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fGJhbGl8ZW58MHx8MHx8&auto=format&fit=crop&w=1000&q=60
      banner-alt-text: Test
      section-styles:
  - label: Text and Image Block
    icon: article
    value: 
      _id: text-img
      title: Text and Img Block
      text_html: Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic dolorum quam recusandae sequi quis asperiores sapiente, temporibus et officiis! Quisquam ut aut dolores distinctio recusandae eum voluptas, modi repellat excepturi!
      content_image: https://images.unsplash.com/photo-1557093793-e196ae071479?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fGJhbGl8ZW58MHx8MHx8&auto=format&fit=crop&w=1000&q=60
      image-alt-text: Test
  - label: Youtube Embed
    icon: article
    value:
      _id: youtube-embed
      title: Youtube Block
      video_url: https://www.youtube.com/embed/CBwKJfrm5-U
  - label: Gallery Block
    icon: article 
    value:
      _id: gallery
      title: Gallery Block
      section-styles:
      gallery_images:
      - gallery_image: https://images.unsplash.com/photo-1557093793-e196ae071479?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fGJhbGl8ZW58MHx8MHx8&auto=format&fit=crop&w=1000&q=60
        image-alt-text: Test
      - gallery_image: https://images.unsplash.com/photo-1557093793-e196ae071479?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fGJhbGl8ZW58MHx8MHx8&auto=format&fit=crop&w=1000&q=60
        image-alt-text: Test
  - label: CTA Block
    icon: article
    value:
      _id: cta
      title: Call to Action Block
      text: Place holder
      button-name: Click here
      button_url: https://www.google.com/
  